development:
  secret_key_base: 5f009d6861a54767b19a3b678197bc8b8b414c8acde5329a01498e293c95b9c7d4c542f616c02ff71cb104d0e926d6839f54c1997d5622486786bcaa8e045640
  sorcery_github_callback_url: <%= ENV["GITHUB_CALLBACK_URL"] %>
  sorcery_github_key: <%= ENV["GITHUB_KEY"] %>
  sorcery_github_secret: <%= ENV["GITHUB_SECRET"] %>

test:
  secret_key_base: 14bdd73d37af27ad9484f7c02f5b59abfbdd52365b03229bbf5b11d6cc17bdc1e4495aa9463f193c258c88e77f484b8548f83de1e960fc2730f30e6e57fcde32
  sorcery_github_key: <%= ENV["GITHUB_KEY"] %>
  sorcery_github_secret: <%= ENV["GITHUB_SECRET"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sorcery_github_callback_url: <%= ENV["GITHUB_CALLBACK_URL"] %>
  sorcery_github_key: <%= ENV["GITHUB_KEY"] %>
  sorcery_github_secret: <%= ENV["GITHUB_SECRET"] %>
